// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class RoleList
    {
        public RoleList()
        {
            Users = new HashSet<Users>();
        }

        public int Id { get; set; }
        public string Authority { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}