// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class SalesHistory
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public decimal? Price { get; set; }
        public DateTime? SaleDate { get; set; }

        public virtual Producto Product { get; set; }
        public virtual Producto User { get; set; }
    }
}