// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class ProductoConfiguration : IEntityTypeConfiguration<Producto>
    {
        public void Configure(EntityTypeBuilder<Producto> entity)
        {
            entity.HasKey(e => e.IdProducto)
                .HasName("PK__Producto__09889210C9160156");

            entity.Property(e => e.Descripcion).HasMaxLength(250);

            entity.Property(e => e.Estado).HasMaxLength(50);

            entity.Property(e => e.Nombre).HasMaxLength(50);

            entity.Property(e => e.Precio).HasColumnType("decimal(18, 0)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Producto> entity);
    }
}
