// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class SalesHistoryConfiguration : IEntityTypeConfiguration<SalesHistory>
    {
        public void Configure(EntityTypeBuilder<SalesHistory> entity)
        {
            entity.Property(e => e.Price).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.SaleDate).HasColumnType("datetime");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.SalesHistoryProduct)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesHist__Produ__3E52440B");

            entity.HasOne(d => d.User)
                .WithMany(p => p.SalesHistoryUser)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesHist__UserI__3F466844");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SalesHistory> entity);
    }
}
